/**
 * Tela theme preset token maps.
 * Each theme defines the complete set of design tokens.
 */

import type { TokenMap } from './types.js';

export const WARM_EDITORIAL: TokenMap = {
  'color.surface.default': '#f5f4ed',
  'color.surface.elevated': '#faf9f5',
  'color.surface.warm': '#e8e6dc',
  'color.surface.inverted': '#141413',
  'color.text.primary': '#141413',
  'color.text.secondary': '#3d3d3a',
  'color.text.caption': '#6b6a64',
  'color.text.accent': '#1B365D',
  'color.text.inverse': '#faf9f5',
  'color.border.subtle': '#e5e3d8',
  'color.border.default': '#e8e6dc',
  'color.border.strong': '#504e49',
  'color.accent.default': '#1B365D',
  'color.accent.tint': '#EEF2F7',
  'color.accent.shade': '#0E1B2F',
  'space.xs': '4px',
  'space.sm': '8px',
  'space.md': '16px',
  'space.lg': '24px',
  'space.xl': '40px',
  'space.section': '80px',
  'type.scale.caption': '12px',
  'type.scale.body': '16px',
  'type.scale.lead': '20px',
  'type.scale.h3': '24px',
  'type.scale.h2': '32px',
  'type.scale.h1': '48px',
  'type.scale.display': '64px',
  'type.weight.body': '400',
  'type.weight.heading': '500',
  'type.weight.emphasis': '500',
  'type.leading.tight': '1.2',
  'type.leading.default': '1.5',
  'type.leading.loose': '1.7',
  'type.family.serif': "Charter, Georgia, 'Palatino Linotype', 'Times New Roman', serif",
  'type.family.sans': "'Inter', 'SF Pro Display', -apple-system, 'Segoe UI', sans-serif",
  'type.family.mono': "'JetBrains Mono', 'SF Mono', 'Fira Code', Consolas, monospace",
  'elevation.flat': 'none',
  'elevation.raised': '0 1px 3px rgba(0,0,0,0.04), 0 4px 12px rgba(0,0,0,0.03)',
  'elevation.floating': '0 4px 24px rgba(0,0,0,0.06)',
  'radius.sm': '4px',
  'radius.md': '8px',
  'radius.lg': '16px',
  'radius.xl': '24px',
  'radius.pill': '999px',
};

export const COOL_TECHNICAL: TokenMap = {
  'color.surface.default': '#f8f9fa',
  'color.surface.elevated': '#ffffff',
  'color.surface.warm': '#e9ecef',
  'color.surface.inverted': '#1a1a2e',
  'color.text.primary': '#212529',
  'color.text.secondary': '#495057',
  'color.text.caption': '#868e96',
  'color.text.accent': '#2563eb',
  'color.text.inverse': '#f8f9fa',
  'color.border.subtle': '#e9ecef',
  'color.border.default': '#dee2e6',
  'color.border.strong': '#495057',
  'color.accent.default': '#2563eb',
  'color.accent.tint': '#eff6ff',
  'color.accent.shade': '#1e40af',
  'space.xs': '4px',
  'space.sm': '8px',
  'space.md': '16px',
  'space.lg': '24px',
  'space.xl': '40px',
  'space.section': '72px',
  'type.scale.caption': '12px',
  'type.scale.body': '15px',
  'type.scale.lead': '18px',
  'type.scale.h3': '22px',
  'type.scale.h2': '30px',
  'type.scale.h1': '44px',
  'type.scale.display': '60px',
  'type.weight.body': '400',
  'type.weight.heading': '600',
  'type.weight.emphasis': '500',
  'type.leading.tight': '1.15',
  'type.leading.default': '1.5',
  'type.leading.loose': '1.65',
  'type.family.serif': "'Source Serif 4', Georgia, serif",
  'type.family.sans': "'Inter', 'SF Pro Display', -apple-system, 'Segoe UI', sans-serif",
  'type.family.mono': "'JetBrains Mono', 'SF Mono', 'Fira Code', Consolas, monospace",
  'elevation.flat': 'none',
  'elevation.raised': '0 1px 2px rgba(0,0,0,0.05), 0 2px 8px rgba(0,0,0,0.04)',
  'elevation.floating': '0 8px 30px rgba(0,0,0,0.08)',
  'radius.sm': '4px',
  'radius.md': '6px',
  'radius.lg': '12px',
  'radius.xl': '20px',
  'radius.pill': '999px',
};

export const NEUTRAL_MINIMAL: TokenMap = {
  'color.surface.default': '#ffffff',
  'color.surface.elevated': '#ffffff',
  'color.surface.warm': '#f5f5f5',
  'color.surface.inverted': '#111111',
  'color.text.primary': '#111111',
  'color.text.secondary': '#555555',
  'color.text.caption': '#888888',
  'color.text.accent': '#111111',
  'color.text.inverse': '#ffffff',
  'color.border.subtle': '#eeeeee',
  'color.border.default': '#dddddd',
  'color.border.strong': '#333333',
  'color.accent.default': '#111111',
  'color.accent.tint': '#f5f5f5',
  'color.accent.shade': '#000000',
  'space.xs': '4px',
  'space.sm': '8px',
  'space.md': '20px',
  'space.lg': '32px',
  'space.xl': '48px',
  'space.section': '96px',
  'type.scale.caption': '11px',
  'type.scale.body': '16px',
  'type.scale.lead': '20px',
  'type.scale.h3': '22px',
  'type.scale.h2': '32px',
  'type.scale.h1': '48px',
  'type.scale.display': '72px',
  'type.weight.body': '400',
  'type.weight.heading': '400',
  'type.weight.emphasis': '500',
  'type.leading.tight': '1.1',
  'type.leading.default': '1.55',
  'type.leading.loose': '1.7',
  'type.family.serif': "'EB Garamond', Garamond, 'Times New Roman', serif",
  'type.family.sans': "'Inter', 'Helvetica Neue', Arial, sans-serif",
  'type.family.mono': "'IBM Plex Mono', 'SF Mono', Consolas, monospace",
  'elevation.flat': 'none',
  'elevation.raised': '0 1px 4px rgba(0,0,0,0.04)',
  'elevation.floating': '0 4px 20px rgba(0,0,0,0.06)',
  'radius.sm': '2px',
  'radius.md': '4px',
  'radius.lg': '8px',
  'radius.xl': '16px',
  'radius.pill': '999px',
};

export const DARK_DRAMATIC: TokenMap = {
  'color.surface.default': '#0a0a0a',
  'color.surface.elevated': '#141414',
  'color.surface.warm': '#1e1e1e',
  'color.surface.inverted': '#f5f5f5',
  'color.text.primary': '#f0f0f0',
  'color.text.secondary': '#a0a0a0',
  'color.text.caption': '#6b6b6b',
  'color.text.accent': '#ff6b35',
  'color.text.inverse': '#0a0a0a',
  'color.border.subtle': '#1e1e1e',
  'color.border.default': '#2a2a2a',
  'color.border.strong': '#555555',
  'color.accent.default': '#ff6b35',
  'color.accent.tint': '#1a1008',
  'color.accent.shade': '#cc4e1a',
  'space.xs': '4px',
  'space.sm': '8px',
  'space.md': '16px',
  'space.lg': '28px',
  'space.xl': '48px',
  'space.section': '88px',
  'type.scale.caption': '12px',
  'type.scale.body': '16px',
  'type.scale.lead': '20px',
  'type.scale.h3': '24px',
  'type.scale.h2': '36px',
  'type.scale.h1': '52px',
  'type.scale.display': '72px',
  'type.weight.body': '400',
  'type.weight.heading': '600',
  'type.weight.emphasis': '500',
  'type.leading.tight': '1.1',
  'type.leading.default': '1.5',
  'type.leading.loose': '1.65',
  'type.family.serif': "'Playfair Display', Georgia, serif",
  'type.family.sans': "'Inter', 'SF Pro Display', -apple-system, sans-serif",
  'type.family.mono': "'JetBrains Mono', 'Fira Code', monospace",
  'elevation.flat': 'none',
  'elevation.raised': '0 2px 8px rgba(0,0,0,0.3)',
  'elevation.floating': '0 8px 40px rgba(0,0,0,0.4)',
  'radius.sm': '4px',
  'radius.md': '8px',
  'radius.lg': '16px',
  'radius.xl': '24px',
  'radius.pill': '999px',
};

export const REPORT: TokenMap = {
  'color.surface.default': '#f8f9fa',
  'color.surface.elevated': '#ffffff',
  'color.surface.warm': '#f0f4f8',
  'color.surface.inverted': '#1e3a5f',
  'color.text.primary': '#0f1923',
  'color.text.secondary': '#4a5568',
  'color.text.caption': '#718096',
  'color.text.accent': '#1e3a5f',
  'color.text.inverse': '#f8f9fa',
  'color.border.subtle': '#e2e8f0',
  'color.border.default': '#cbd5e0',
  'color.border.strong': '#4a5568',
  'color.accent.default': '#1e3a5f',
  'color.accent.tint': '#e8edf4',
  'color.accent.shade': '#152c47',
  'space.xs': '4px',
  'space.sm': '8px',
  'space.md': '16px',
  'space.lg': '24px',
  'space.xl': '36px',
  'space.section': '56px',
  'type.scale.caption': '11px',
  'type.scale.body': '15px',
  'type.scale.lead': '18px',
  'type.scale.h3': '22px',
  'type.scale.h2': '28px',
  'type.scale.h1': '40px',
  'type.scale.display': '56px',
  'type.weight.body': '400',
  'type.weight.heading': '600',
  'type.weight.emphasis': '500',
  'type.leading.tight': '1.2',
  'type.leading.default': '1.6',
  'type.leading.loose': '1.8',
  'type.family.serif': "'IBM Plex Serif', Georgia, serif",
  'type.family.sans': "'IBM Plex Sans', 'Helvetica Neue', Arial, sans-serif",
  'type.family.mono': "'IBM Plex Mono', 'Courier New', monospace",
  'elevation.flat': 'none',
  'elevation.raised': '0 1px 3px rgba(0,0,0,0.10), 0 1px 2px rgba(0,0,0,0.06)',
  'elevation.floating': '0 4px 16px rgba(0,0,0,0.12)',
  'radius.sm': '3px',
  'radius.md': '6px',
  'radius.lg': '10px',
  'radius.xl': '16px',
  'radius.pill': '999px',
};

export const PITCH: TokenMap = {
  'color.surface.default': '#ffffff',
  'color.surface.elevated': '#f9f9ff',
  'color.surface.warm': '#f3f0ff',
  'color.surface.inverted': '#18103a',
  'color.text.primary': '#0f0a1e',
  'color.text.secondary': '#5b5478',
  'color.text.caption': '#8b82a7',
  'color.text.accent': '#7c3aed',
  'color.text.inverse': '#f9f9ff',
  'color.border.subtle': '#ede9fe',
  'color.border.default': '#ddd6fe',
  'color.border.strong': '#7c3aed',
  'color.accent.default': '#7c3aed',
  'color.accent.tint': '#ede9fe',
  'color.accent.shade': '#5b21b6',
  'space.xs': '4px',
  'space.sm': '8px',
  'space.md': '16px',
  'space.lg': '28px',
  'space.xl': '48px',
  'space.section': '96px',
  'type.scale.caption': '12px',
  'type.scale.body': '16px',
  'type.scale.lead': '20px',
  'type.scale.h3': '26px',
  'type.scale.h2': '36px',
  'type.scale.h1': '56px',
  'type.scale.display': '72px',
  'type.weight.body': '400',
  'type.weight.heading': '700',
  'type.weight.emphasis': '600',
  'type.leading.tight': '1.1',
  'type.leading.default': '1.5',
  'type.leading.loose': '1.7',
  'type.family.serif': "'Space Grotesk', 'Inter', sans-serif",
  'type.family.sans': "'Inter', 'Helvetica Neue', Arial, sans-serif",
  'type.family.mono': "'JetBrains Mono', 'Courier New', monospace",
  'elevation.flat': 'none',
  'elevation.raised': '0 2px 8px rgba(124,58,237,0.10)',
  'elevation.floating': '0 8px 32px rgba(124,58,237,0.18)',
  'radius.sm': '6px',
  'radius.md': '12px',
  'radius.lg': '20px',
  'radius.xl': '28px',
  'radius.pill': '999px',
};

export const ACADEMIC: TokenMap = {
  'color.surface.default': '#ffffff',
  'color.surface.elevated': '#fafaf8',
  'color.surface.warm': '#f5f5f0',
  'color.surface.inverted': '#1a1a1a',
  'color.text.primary': '#111111',
  'color.text.secondary': '#444444',
  'color.text.caption': '#666666',
  'color.text.accent': '#1a3a6b',
  'color.text.inverse': '#fafaf8',
  'color.border.subtle': '#e8e8e0',
  'color.border.default': '#cccccc',
  'color.border.strong': '#333333',
  'color.accent.default': '#1a3a6b',
  'color.accent.tint': '#eef2f9',
  'color.accent.shade': '#122851',
  'space.xs': '4px',
  'space.sm': '8px',
  'space.md': '16px',
  'space.lg': '24px',
  'space.xl': '40px',
  'space.section': '64px',
  'type.scale.caption': '11px',
  'type.scale.body': '17px',
  'type.scale.lead': '20px',
  'type.scale.h3': '22px',
  'type.scale.h2': '26px',
  'type.scale.h1': '34px',
  'type.scale.display': '44px',
  'type.weight.body': '400',
  'type.weight.heading': '400',
  'type.weight.emphasis': '400',
  'type.leading.tight': '1.3',
  'type.leading.default': '1.7',
  'type.leading.loose': '2.0',
  'type.family.serif': "'EB Garamond', Georgia, 'Times New Roman', serif",
  'type.family.sans': "'EB Garamond', Georgia, serif",
  'type.family.mono': "'IBM Plex Mono', 'Courier New', monospace",
  'elevation.flat': 'none',
  'elevation.raised': '0 1px 3px rgba(0,0,0,0.08)',
  'elevation.floating': '0 2px 8px rgba(0,0,0,0.10)',
  'radius.sm': '2px',
  'radius.md': '3px',
  'radius.lg': '4px',
  'radius.xl': '6px',
  'radius.pill': '999px',
};

export const THEME_PRESETS: Record<string, TokenMap> = {
  'warm-editorial': WARM_EDITORIAL,
  'cool-technical': COOL_TECHNICAL,
  'neutral-minimal': NEUTRAL_MINIMAL,
  'dark-dramatic': DARK_DRAMATIC,
  'report': REPORT,
  'pitch': PITCH,
  'academic': ACADEMIC,
};
